/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.interfaces;

import com.connection.DbConnection;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.imageio.ImageIO;
import java.io.ByteArrayOutputStream;

/**
 *
 * @author Theekshana
 */
public class Add_Student extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;

    String uploaded_profile_picture_path = "";

    Students parentPanel;

    public Add_Student(Students aThis) {

        conn = DbConnection.connect();

        initComponents();
        FlatSVGIcon myIcon = new FlatSVGIcon("com/images/user-3296.svg", 128, 128);

// 2. Label ekata icon eka set karanna
        jLabel1.setIcon(myIcon);

// 3. Text eka epa nam eka remove karන්න
        jLabel1.setText("");
        
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);

        this.parentPanel = aThis;
    }

    //Qr Code Generate Code
    public BufferedImage generateQRCode(String text, int width, int height) throws Exception {
        QRCodeWriter qrCodeWriter = new QRCodeWriter();
        BitMatrix bitMatrix = qrCodeWriter.encode(text, BarcodeFormat.QR_CODE, width, height);

        return MatrixToImageWriter.toBufferedImage(bitMatrix);
    }

    private byte[] getQRCodeBytes(BufferedImage image) throws Exception {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        ImageIO.write(image, "png", baos);
        return baos.toByteArray();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        name_box = new javax.swing.JTextField();
        birthday_box = new javax.swing.JTextField();
        school_box = new javax.swing.JTextField();
        nic_box = new javax.swing.JTextField();
        student_contact_no_box = new javax.swing.JTextField();
        parent_name_box = new javax.swing.JTextField();
        parent_contact_no_box = new javax.swing.JTextField();
        Insert_button = new javax.swing.JButton();
        address_box = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        maths = new javax.swing.JRadioButton();
        bio = new javax.swing.JRadioButton();
        commerce = new javax.swing.JRadioButton();
        arts = new javax.swing.JRadioButton();
        tec = new javax.swing.JRadioButton();
        email_box = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        student_name_validation_box = new javax.swing.JLabel();
        birthday_validation_box = new javax.swing.JLabel();
        school_validation_box = new javax.swing.JLabel();
        nic_no_validation_box = new javax.swing.JLabel();
        gender_validation_box = new javax.swing.JLabel();
        address_validation_box = new javax.swing.JLabel();
        student_contact_no_validation_box = new javax.swing.JLabel();
        email_validation_box = new javax.swing.JLabel();
        parent_name_validation_box = new javax.swing.JLabel();
        parent_contact_no_validation_box = new javax.swing.JLabel();
        subject_stream_validation_box = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(11, 45, 114));

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Add Student");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jLabel2.setText("Full Name");

        jLabel3.setText("Date of Birth");

        jLabel4.setText("School");

        jLabel5.setText("NIC No");

        jLabel6.setText("Gender");

        jLabel7.setText("Student Contact Number");

        jLabel8.setText("Parent Name");

        jLabel9.setText("Parent Contact Number");

        name_box.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                name_boxFocusLost(evt);
            }
        });
        name_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_boxActionPerformed(evt);
            }
        });

        birthday_box.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                birthday_boxFocusLost(evt);
            }
        });
        birthday_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthday_boxActionPerformed(evt);
            }
        });

        school_box.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                school_boxFocusLost(evt);
            }
        });
        school_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                school_boxActionPerformed(evt);
            }
        });

        nic_box.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nic_boxFocusLost(evt);
            }
        });

        student_contact_no_box.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                student_contact_no_boxFocusLost(evt);
            }
        });
        student_contact_no_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_contact_no_boxActionPerformed(evt);
            }
        });

        parent_name_box.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                parent_name_boxFocusLost(evt);
            }
        });
        parent_name_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parent_name_boxActionPerformed(evt);
            }
        });

        parent_contact_no_box.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                parent_contact_no_boxFocusLost(evt);
            }
        });

        Insert_button.setText("Add Student");
        Insert_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert_buttonActionPerformed(evt);
            }
        });

        address_box.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                address_boxFocusLost(evt);
            }
        });
        address_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_boxActionPerformed(evt);
            }
        });

        jLabel10.setText("Address");

        buttonGroup1.add(male);
        male.setText("Male");

        buttonGroup1.add(female);
        female.setText("Female");

        jLabel11.setText("Subject Stream");

        buttonGroup2.add(maths);
        maths.setText("Maths");
        maths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathsActionPerformed(evt);
            }
        });

        buttonGroup2.add(bio);
        bio.setText("Bio");
        bio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bioActionPerformed(evt);
            }
        });

        buttonGroup2.add(commerce);
        commerce.setText("Commerce");
        commerce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commerceActionPerformed(evt);
            }
        });

        buttonGroup2.add(arts);
        arts.setText("Arts ");
        arts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artsActionPerformed(evt);
            }
        });

        buttonGroup2.add(tec);
        tec.setText("Technology ");
        tec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecActionPerformed(evt);
            }
        });

        email_box.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                email_boxFocusLost(evt);
            }
        });
        email_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_boxActionPerformed(evt);
            }
        });

        jLabel13.setText("Email");

        jLabel15.setText("Student Profile Picture");

        jButton1.setText("Upload Profile Picture");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        student_name_validation_box.setForeground(new java.awt.Color(204, 51, 0));

        birthday_validation_box.setForeground(new java.awt.Color(204, 51, 0));

        school_validation_box.setForeground(new java.awt.Color(204, 51, 0));

        nic_no_validation_box.setForeground(new java.awt.Color(204, 51, 0));

        gender_validation_box.setForeground(new java.awt.Color(204, 51, 0));

        address_validation_box.setForeground(new java.awt.Color(204, 51, 0));

        student_contact_no_validation_box.setForeground(new java.awt.Color(204, 51, 0));

        email_validation_box.setForeground(new java.awt.Color(204, 51, 0));

        parent_name_validation_box.setForeground(new java.awt.Color(204, 51, 0));

        parent_contact_no_validation_box.setForeground(new java.awt.Color(204, 51, 0));

        subject_stream_validation_box.setForeground(new java.awt.Color(204, 51, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(student_name_validation_box)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(male, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(female, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(maths, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(commerce, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(arts, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(parent_name_box)
                                .addComponent(address_box)
                                .addComponent(nic_box)
                                .addComponent(school_box)
                                .addComponent(birthday_box)
                                .addComponent(name_box)
                                .addComponent(student_contact_no_box)
                                .addComponent(parent_contact_no_box)
                                .addComponent(email_box, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(birthday_validation_box)
                            .addComponent(school_validation_box)
                            .addComponent(nic_no_validation_box)
                            .addComponent(gender_validation_box)
                            .addComponent(address_validation_box)
                            .addComponent(student_contact_no_validation_box)
                            .addComponent(email_validation_box)
                            .addComponent(parent_name_validation_box)
                            .addComponent(parent_contact_no_validation_box)
                            .addComponent(subject_stream_validation_box)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(Insert_button, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name_box, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(student_name_validation_box)
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(birthday_box, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(birthday_validation_box)
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(school_box, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(school_validation_box)
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nic_box, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(nic_no_validation_box)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(male)
                    .addComponent(female))
                .addGap(3, 3, 3)
                .addComponent(gender_validation_box)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(address_box, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(address_validation_box)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(student_contact_no_box, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(student_contact_no_validation_box)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(email_box, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email_validation_box)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(parent_name_box, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(parent_name_validation_box)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(parent_contact_no_box, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(parent_contact_no_validation_box)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(maths)
                    .addComponent(bio)
                    .addComponent(commerce)
                    .addComponent(arts)
                    .addComponent(tec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subject_stream_validation_box)
                .addGap(34, 34, 34)
                .addComponent(Insert_button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mathsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathsActionPerformed

    }//GEN-LAST:event_mathsActionPerformed

    private void bioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bioActionPerformed

    }//GEN-LAST:event_bioActionPerformed

    private void commerceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commerceActionPerformed

    }//GEN-LAST:event_commerceActionPerformed

    private void artsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artsActionPerformed

    }//GEN-LAST:event_artsActionPerformed

    private void tecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecActionPerformed

    }//GEN-LAST:event_tecActionPerformed

    private void name_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_boxActionPerformed
        birthday_box.grabFocus();
    }//GEN-LAST:event_name_boxActionPerformed

    private void birthday_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthday_boxActionPerformed
        school_box.grabFocus();
    }//GEN-LAST:event_birthday_boxActionPerformed

    private void school_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_school_boxActionPerformed
        nic_box.grabFocus();
    }//GEN-LAST:event_school_boxActionPerformed

    private void address_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_boxActionPerformed
        student_contact_no_box.grabFocus();
    }//GEN-LAST:event_address_boxActionPerformed

    private void student_contact_no_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_contact_no_boxActionPerformed
        email_box.grabFocus();
    }//GEN-LAST:event_student_contact_no_boxActionPerformed

    private void email_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_boxActionPerformed
        parent_name_box.grabFocus();
    }//GEN-LAST:event_email_boxActionPerformed

    private void parent_name_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parent_name_boxActionPerformed
        parent_contact_no_box.grabFocus();
    }//GEN-LAST:event_parent_name_boxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Image Files", "jpg", "png", "jpeg"));

        if (chooser.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file = chooser.getSelectedFile();

            try {
                // 1. Image eka read kirima
                java.awt.Image img = javax.imageio.ImageIO.read(file);

                // 2. Resize kirima (128x128)
                java.awt.Image resizedImg = img.getScaledInstance(228, 228, java.awt.Image.SCALE_SMOOTH);

                // 3. Label ekata image eka set kirima (Preview)
                jLabel1.setIcon(new javax.swing.ImageIcon(resizedImg));

                // 4. Save karanna ona path eka hadaganna
                // 'com/images' kiyana folder ekata aluth namakin save karanawa (System time eka use kala mix nowenna)
                String fileName = System.currentTimeMillis() + "_" + file.getName();
                String destinationPath = "src/com/profile_images/" + fileName;

                // 5. Image eka project folder ekata save kirima
                java.io.File outputFile = new java.io.File(destinationPath);
                javax.imageio.ImageIO.write(toBufferedImage(resizedImg), "png", outputFile);

                // 6. Me variable eka thama Database ekata danna oni (Path eka)
                uploaded_profile_picture_path = destinationPath;

                System.out.println("Saved to: " + uploaded_profile_picture_path);

            } catch (Exception ex) {
                ex.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Error processing image", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Insert_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insert_buttonActionPerformed
        check_validations();
    }//GEN-LAST:event_Insert_buttonActionPerformed

    private void name_boxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_name_boxFocusLost
        valid_student_name();
    }//GEN-LAST:event_name_boxFocusLost

    private void birthday_boxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_birthday_boxFocusLost
        valid_birthday();
    }//GEN-LAST:event_birthday_boxFocusLost

    private void school_boxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_school_boxFocusLost
       valid_school();
    }//GEN-LAST:event_school_boxFocusLost

    private void nic_boxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nic_boxFocusLost
        valid_nic();
    }//GEN-LAST:event_nic_boxFocusLost

    private void address_boxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_address_boxFocusLost
        valid_address();
    }//GEN-LAST:event_address_boxFocusLost

    private void student_contact_no_boxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_student_contact_no_boxFocusLost
        valid_student_contact_no();
    }//GEN-LAST:event_student_contact_no_boxFocusLost

    private void email_boxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_boxFocusLost
        valid_mail();
    }//GEN-LAST:event_email_boxFocusLost

    private void parent_name_boxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_parent_name_boxFocusLost
        valid_parent_name();
    }//GEN-LAST:event_parent_name_boxFocusLost

    private void parent_contact_no_boxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_parent_contact_no_boxFocusLost
        valid_parent_contact_no();
    }//GEN-LAST:event_parent_contact_no_boxFocusLost

    public void insert_student() {

        String name = name_box.getText();
        String birthday = birthday_box.getText();
        String school = school_box.getText();
        String nic_no = nic_box.getText();
        String gender = "";
        String address = address_box.getText();
        String student_contact_no = student_contact_no_box.getText();
        String email = email_box.getText();
        String parent_name = parent_name_box.getText();
        String parent_contact_no = parent_contact_no_box.getText();
        String subject_stream = "";
//        String subjects = String.join("", selectedSubjects);
//        String classes = String.join("", selectedClasses);
        String profile_picture = "";
        String data = nic_box.getText();

        //Profile Pictures
//        FlatSVGIcon male_img = new FlatSVGIcon("com/images/male.svg", 128, 90);
//        FlatSVGIcon female_img = new FlatSVGIcon("com/images/female.svg", 128, 90);
        if (male.isSelected()) {
            gender = "Male";
        } else if (female.isSelected()) {
            gender = "Female";
        }

        if (!uploaded_profile_picture_path.isEmpty()) {
            profile_picture = uploaded_profile_picture_path;
        }

        if (maths.isSelected()) {
            subject_stream = "Maths";
        } else if (bio.isSelected()) {
            subject_stream = "Bio";
        } else if (commerce.isSelected()) {
            subject_stream = "Commerce";
        } else if (arts.isSelected()) {
            subject_stream = "Arts";
        } else if (tec.isSelected()) {
            subject_stream = "Tec";
        }

        try {
            // 1. QR eka generate karagannawa
            BufferedImage qr_image = generateQRCode(data, 250, 250);

            // 2. Image eka byte array ekakata harawanawa database ekata danna
            byte[] qr_code_bytes = getQRCodeBytes(qr_image);

            String query = "INSERT INTO students (name, birthday, school, nic_no, gender, address, student_contact_no, email, parent_name, parent_contact_no, subject_stream, profile_picture, qr_code) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";

            pst = conn.prepareStatement(query);

            pst.setString(1, name);
            pst.setString(2, birthday);
            pst.setString(3, school);
            pst.setString(4, nic_no);
            pst.setString(5, gender);
            pst.setString(6, address);
            pst.setString(7, student_contact_no);
            pst.setString(8, email);
            pst.setString(9, parent_name);
            pst.setString(10, parent_contact_no);
            pst.setString(11, subject_stream);
            pst.setString(12, profile_picture);

            // 3. QR code eka BLOB ekak widiyata set kirima
            pst.setBytes(13, qr_code_bytes);

            pst.execute();

            JOptionPane.showMessageDialog(null, "Student Added Successfully!");
            clear();

            if (parentPanel != null) {
                parentPanel.view_data();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        }

    }

    public void clear() {
        uploaded_profile_picture_path = "";
        jLabel1.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("com/images/user-3296.svg", 128, 128));

        name_box.setText("");
        birthday_box.setText("");
        school_box.setText("");
        nic_box.setText("");
        buttonGroup1.clearSelection();
        address_box.setText("");
        student_contact_no_box.setText("");
        email_box.setText("");
        parent_name_box.setText("");
        parent_contact_no_box.setText("");
        buttonGroup2.clearSelection();

    }

    public static java.awt.image.BufferedImage toBufferedImage(java.awt.Image img) {
        if (img instanceof java.awt.image.BufferedImage) {
            return (java.awt.image.BufferedImage) img;
        }
        java.awt.image.BufferedImage bimage = new java.awt.image.BufferedImage(
                img.getWidth(null), img.getHeight(null), java.awt.image.BufferedImage.TYPE_INT_ARGB);
        java.awt.Graphics2D bGr = bimage.createGraphics();
        bGr.drawImage(img, 0, 0, null);
        bGr.dispose();
        return bimage;
    }

    //Validations
    public void check_validations(){
    
        if(valid_student_name() && valid_birthday() && valid_school() && valid_nic() && valid_gender()
                && valid_address() && valid_student_contact_no() && valid_mail() && valid_parent_name()
                && valid_parent_contact_no() && valid_subject_stream()){
        
            insert_student();
        }else{
            JOptionPane.showMessageDialog(null, "Check the Validations Please!");
        }
        
    }
    
    public boolean valid_student_name() {

        String data = name_box.getText();
        String method = "^[A-Z][a-z.]*\\s[A-Z][a-z.]*(\\s[A-Z][a-z.]*)*$";

        if (!data.matches(method)) {
            student_name_validation_box.setText("Validation Failed!");
            return false;
        } else {
            student_name_validation_box.setText("");
            return true;
        }

    }

    public boolean valid_birthday() {

        String data = birthday_box.getText();
        String method = "^(19|20)\\d\\d-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$";

        if (!data.matches(method)) {
            birthday_validation_box.setText("Validation Failed!");
            return false;
        } else {
            birthday_validation_box.setText("");
            return true;
        }

    }

    public boolean valid_school() {

        String data = school_box.getText();
        String method = "^[a-zA-Z\\s\\.,'\\(\\)\\-]+$";

        if (!data.matches(method)) {
            school_validation_box.setText("Validation Failed!");
            return false;
        } else {
            school_validation_box.setText("");
            return true;
        }

    }

    public boolean valid_nic() {

        String data = nic_box.getText();
        String method = "^([0-9]{9}[vVxX]|[0-9]{12})$";

        if (!data.matches(method)) {
            nic_no_validation_box.setText("Validation Failed!");
            return false;
        } else {
            nic_no_validation_box.setText("");
            return true;
        }

    }

    public boolean valid_gender() {

        if(buttonGroup1.getSelection() == null){
            gender_validation_box.setText("Validation Failed!");
            return false;
        }else{
            gender_validation_box.setText("");
            return true;
        }
    }

    public boolean valid_address() {

        String data = address_box.getText();
        String method = "^[a-zA-Z0-9\\s.,\\-\\/]+$";

        if (!data.matches(method)) {
            address_validation_box.setText("Validation Failed!");
            return false;
        } else {
            address_validation_box.setText("");
            return true;
        }

    }

    public boolean valid_student_contact_no() {

        String data = student_contact_no_box.getText();
        String method = "^(0|\\\\+94)[0-9]{9}$";

        if (!data.matches(method)) {
            student_contact_no_validation_box.setText("Validation Failed!");
            return false;
        } else {
            student_contact_no_validation_box.setText("");
            return true;
        }

    }

    public boolean valid_mail() {

        String data = email_box.getText();
        String method = "^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$";

        if (!data.matches(method)) {
            email_validation_box.setText("Validation Failed!");
            return false;
        } else {
            email_validation_box.setText("");
            return true;
        }

    }

    public boolean valid_parent_name() {

        String data = parent_name_box.getText();
        String method = "^[A-Z][a-z.]*\\s[A-Z][a-z.]*(\\s[A-Z][a-z.]*)*$";

        if (!data.matches(method)) {
            parent_name_validation_box.setText("Validation Failed!");
            return false;
        } else {
            parent_name_validation_box.setText("");
            return true;
        }

    }
    
    public boolean valid_parent_contact_no() {

        String data = parent_contact_no_box.getText();
        String method = "^(0|\\\\+94)[0-9]{9}$";

        if (!data.matches(method)) {
            parent_contact_no_validation_box.setText("Validation Failed!");
            return false;
        } else {
            parent_contact_no_validation_box.setText("");
            return true;
        }

    }
    
    public boolean valid_subject_stream() {

        if(buttonGroup2.getSelection() == null){
            subject_stream_validation_box.setText("Validation Failed!");
            return false;
        }else{
            subject_stream_validation_box.setText("");
            return true;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Insert_button;
    private javax.swing.JTextField address_box;
    private javax.swing.JLabel address_validation_box;
    private javax.swing.JRadioButton arts;
    private javax.swing.JRadioButton bio;
    private javax.swing.JTextField birthday_box;
    private javax.swing.JLabel birthday_validation_box;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton commerce;
    private javax.swing.JTextField email_box;
    private javax.swing.JLabel email_validation_box;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel gender_validation_box;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton maths;
    private javax.swing.JTextField name_box;
    private javax.swing.JTextField nic_box;
    private javax.swing.JLabel nic_no_validation_box;
    private javax.swing.JTextField parent_contact_no_box;
    private javax.swing.JLabel parent_contact_no_validation_box;
    private javax.swing.JTextField parent_name_box;
    private javax.swing.JLabel parent_name_validation_box;
    private javax.swing.JTextField school_box;
    private javax.swing.JLabel school_validation_box;
    private javax.swing.JTextField student_contact_no_box;
    private javax.swing.JLabel student_contact_no_validation_box;
    private javax.swing.JLabel student_name_validation_box;
    private javax.swing.JLabel subject_stream_validation_box;
    private javax.swing.JRadioButton tec;
    // End of variables declaration//GEN-END:variables
}
