/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.interfaces;

import com.connection.DbConnection;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author theekshana
 */
public class Add_Subjects extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    Students parentPanel;

    public Add_Subjects(String student_id, String subject_stream, Students aThis) {
        initComponents();

        conn = DbConnection.connect();

        student_id_box.setText(student_id);
        subject_stream_box.setText(subject_stream);

        this.parentPanel = aThis;

        get_subjects();
        get_classes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        subject_box = new javax.swing.JComboBox<>();
        class_box = new javax.swing.JComboBox<>();
        Insert_button = new javax.swing.JButton();
        student_id_box = new javax.swing.JLabel();
        subject_stream_box = new javax.swing.JLabel();
        class_id_box = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel14.setText("Classes");

        jLabel12.setText("Subjects");

        subject_box.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                subject_boxItemStateChanged(evt);
            }
        });

        Insert_button.setText("Add Subject");
        Insert_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert_buttonActionPerformed(evt);
            }
        });

        student_id_box.setText("jLabel2");

        subject_stream_box.setText("jLabel2");

        class_id_box.setText("jLabel2");

        jPanel1.setBackground(new java.awt.Color(11, 45, 114));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Subjects");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(Insert_button, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 285, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(subject_box, 0, 495, Short.MAX_VALUE)
                            .addComponent(class_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(class_id_box, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(subject_stream_box, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(student_id_box, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(student_id_box)
                    .addComponent(subject_stream_box)
                    .addComponent(class_id_box))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subject_box, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(class_box, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(63, 63, 63)
                .addComponent(Insert_button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void subject_boxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_subject_boxItemStateChanged
        get_classes();
    }//GEN-LAST:event_subject_boxItemStateChanged

    private void Insert_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insert_buttonActionPerformed
        insert_data();
    }//GEN-LAST:event_Insert_buttonActionPerformed

    public void get_subjects() {

        String[] maths = {"Combined Mathematics", "Physics", "Chemistry", "Information & Communication Technology (ICT)"};

        String[] bio = {"Biology", "Chemistry", "Physics", "Agricultural Science"};

        String[] commerce = {"Accounting", "Business Studies", "Economics", "Information & Communication Technology (ICT)", "Business Statistics"};

        String[] arts = {"Sinhala", "Tamil", "English", "Japanese", "Economics", "Geography", "History (Sri Lankan, Indian, European or Modern)", "Political Science", "Logic and Scientific Method",
            "Home Economics", "Buddhist Civilization", "Hindu Civilization", "Islam Civilization", "Christian Civilization", "Greek and Roman Civilization",
            "Mass Media and Communication Studies", "Dancing (Eastern/Western)", "Music (Eastern/Western)", "Drama and Theatre", "Art"};

        String[] tec = {"Engineering Technology (ET)", "Bio-System Technology (BST)", "Science for Technology (SFT)", "Information & Communication Technology (ICT)",
            "Agricultural Science"};

        if (subject_stream_box.getText().equals("Maths")) {
            subject_box.removeAll();
            subject_box.setModel(new javax.swing.DefaultComboBoxModel<>(maths));
        } else if (subject_stream_box.getText().equals("Bio")) {
            subject_box.removeAll();
            subject_box.setModel(new javax.swing.DefaultComboBoxModel<>(bio));
        } else if (subject_stream_box.getText().equals("Commerce")) {
            subject_box.removeAll();
            subject_box.setModel(new javax.swing.DefaultComboBoxModel<>(commerce));
        } else if (subject_stream_box.getText().equals("Arts")) {
            subject_box.removeAll();
            subject_box.setModel(new javax.swing.DefaultComboBoxModel<>(arts));
        } else if (subject_stream_box.getText().equals("Tec")) {
            subject_box.removeAll();
            subject_box.setModel(new javax.swing.DefaultComboBoxModel<>(tec));
        }

    }

    public void get_classes() {

        String selected_subject = subject_box.getSelectedItem().toString();
        class_box.removeAllItems();

        try {

            String query = "SELECT c.class_id, c.day, c.start_time, c.end_time, c.batch, t.name "
                    + "FROM classes c "
                    + "JOIN teachers t ON c.epf_no = t.epf_no " // Menna methana space ekak danna
                    + "WHERE c.subject = ?";

            pst = conn.prepareStatement(query);
            pst.setString(1, selected_subject);
            rs = pst.executeQuery();

            while (rs.next()) {

                String class_id = rs.getString("class_id");
                String teacher_name = rs.getString("name");
                String day = rs.getString("day");
                String start_time = rs.getString("start_time");
                String end_time = rs.getString("end_time");
                String batch = rs.getString("batch");

                class_id_box.setText(class_id);

                String values = teacher_name + " | " + batch + " | " + day + " | " + start_time + " " + "To" + " " + end_time;

                class_box.addItem(values);

            }

        } catch (Exception e) {

            System.out.println("Error: " + e.getMessage());

        }

    }

    public void insert_data() {

        String subject = subject_box.getSelectedItem().toString();
        String student_id = student_id_box.getText();
        String class_id = class_id_box.getText();

        try {

            String query = "INSERT INTO students_classes (subject, student_id, class_id) VALUES (?,?,?)";

            pst = conn.prepareStatement(query);

            pst.setString(1, subject);
            pst.setString(2, student_id);
            pst.setString(3, class_id);

            pst.execute();

            JOptionPane.showMessageDialog(null, "Student Added Successfully!");
            clear();

            if (parentPanel != null) {
                parentPanel.view_data();
            }

        } catch (Exception e) {
        }

    }

    public void clear() {

        subject_box.setSelectedIndex(0);
        class_box.setSelectedIndex(0);
        class_id_box.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Insert_button;
    private javax.swing.JComboBox<String> class_box;
    private javax.swing.JLabel class_id_box;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel student_id_box;
    private javax.swing.JComboBox<String> subject_box;
    private javax.swing.JLabel subject_stream_box;
    // End of variables declaration//GEN-END:variables
}
